server:
  host: 0.0.0.0
  port: 8080
  base-url: /glance

branding:
  app-name: Pure Glance

theme:
  background-color: 220 16 22
  primary-color: 193 43 67
  positive-color: 92 28 65
  negative-color: 354 42 56
  contrast-multiplier: 1.1
  text-saturation-multiplier: 0.9
  presets:
    tokyo-night:
      background-color: 235 19 13
      primary-color: 222 89 72
      positive-color: 88 56 61
      negative-color: 349 89 72
      contrast-multiplier: 1.2
      text-saturation-multiplier: 0.9
    catppuccin:
      background-color: 240 21 15
      primary-color: 267 84 81
      positive-color: 115 54 76
      negative-color: 343 81 75
      contrast-multiplier: 1.2
      text-saturation-multiplier: 0.9
    rose-pine:
      background-color: 249 22 12
      primary-color: 2 55 83
      positive-color: 197 49 38
      negative-color: 343 76 68
      contrast-multiplier: 1.2
      text-saturation-multiplier: 0.9
    forest:
      background-color: 154 39 7
      primary-color: 160 84 39
      positive-color: 158 64 52
      negative-color: 350 89 60
      contrast-multiplier: 1.2
      text-saturation-multiplier: 0.9
    solarized-light:
      light: true
      background-color: 44 87 94
      primary-color: 205 69 49
      positive-color: 68 100 30
      negative-color: 1 71 52
      contrast-multiplier: 1.2
      text-saturation-multiplier: 0.8

pages:
  - name: Pure Suite
    width: wide
    center-vertically: false
    columns:
      - size: small
        widgets:
          - type: clock
            time-format: 12h
            timezones:
              - timezone: Local
                label: Local Time

          - type: monitor
            title: Pure Suite
            cache: 30s
            sites:
              - title: Pure Feed
                url: /feed/
                icon: si:twitch
              - title: Pure OTP
                url: /otp/
                icon: si:auth0
              - title: Pure Read
                url: /read/
                icon: si:readme
              - title: Pure Note
                url: /note/
                icon: si:markdown
              - title: Pure Clone
                url: /clone/
                icon: si:rclone
              - title: Pure Ping
                url: /ping/
                icon: si:pulse

          - type: bookmarks
            groups:
              - title: Navigation
                links:
                  - title: Pure Feed
                    url: /feed/
                    same-tab: true
                  - title: Pure OTP
                    url: /otp/
                    same-tab: true
                  - title: Pure Read
                    url: /read/
                    same-tab: true
                  - title: Pure Note
                    url: /note/
                    same-tab: true
                  - title: Pure Clone
                    url: /clone/
                    same-tab: true
                  - title: Pure Ping
                    url: /ping/
                    same-tab: true

      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: docker-containers
            title: Docker Stack
            sock-path: /var/run/docker.sock
            running-only: false

          - type: bookmarks
            groups:
              - title: Homelab
                links:
                  - title: Proxmox VE
                    url: https://pve.lan
                  - title: Traefik
                    url: https://traefik.lan
                  - title: Docker Swarm
                    url: https://portainer.lan
              - title: Repositories
                links:
                  - title: GitHub (mcnarya)
                    url: https://github.com/mcnarya
                  - title: Pure App
                    url: https://github.com/mcnarya/pure-app
                  - title: Pure Glance
                    url: https://github.com/mcnarya/pure-glance
